services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      - WATCHTOWER_SCHEDULE=${WATCHTOWER_SCHEDULE:-0 0 4 * * *}
      - TZ=Europe/Paris
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/.docker/config.json:/config.json
  db:
    image: postgres:latest
    container_name: hopital-db
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./hopital-db:/var/lib/postgresql/data
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  api:
    image: registry.selutech.fr/hopital-api:latest
    container_name: hopital-api
    restart: always
    ports:
      - ${HOPITAL_API_PORT:-8081}:8081
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_URL=${POSTGRES_URL:-hopital-db}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - APPLICATION_URL
      - MAIL_SMTP_HOST
      - MAIL_SMTP_PORT
      - MAIL_ADDRESS_FROM
      - MAIL_ADDRESS_SUPPORT=${MAIL_ADDRESS_SUPPORT:-support@hnfc.fr}
      - MAIL_SMTP_AUTH=${MAIL_SMTP_AUTH:-false}
      - MAIL_SMTP_USER=${MAIL_SMTP_USER:-''}
      - MAIL_SMTP_PASSWORD=${MAIL_SMTP_PASSWORD:-''}
      - MAIL_SMTP_STARTTTLS_ENABLE=${MAIL_SMTP_STARTTTLS_ENABLE:-false}
      - MAIL_SMTP_STARTTTLS_REQUIRED=${MAIL_SMTP_STARTTTLS_REQUIRED:-false}
      - PRE_SUBJECT_TITLE=${PRE_SUBJECT_TITLE:-Suivi de la douleur}
      - PASSWORD_RESET_TOKEN_EXPIRATION=${PASSWORD_RESET_TOKEN_EXPIRATION:-15}
    volumes:
      - ./hopital-api/logs:/logs
    depends_on:
      - db
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  web:
    image: registry.selutech.fr/hopital:${HOPITAL_VERSION:-latest}
    container_name: hopital-web
    restart: always
    ports:
      - ${HOPITAL_WEB_PORT:-8082}:8082
    depends_on:
      - api
    networks:
      - default
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
